language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registrations

node_js:  
  - "12.18.3"

before_script:
  - psql -c 'create database  registrations;' -U postgres
  - psql -U postgres -d registrations -a -f reg.sql

services:
  - postgresql